config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  
  root 'welcome#index' # reference is root_path
  get 'my_shopping', to: "users#my_shopping"
  resources :items
  resources :categories
  

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true, length: {minimum: 3, maximum: 50}
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  validates :name, presence: true, length: {minimum: 3, maximum: 50}
  validates :price, presence: true
  validates :date, presence: true
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :items, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  
  helper_method :current_user, :logged_in?
  
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id] 
  end
  
  def logged_in?
   !!current_user
  end
  
  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action!"
      redirect_to root_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:edit, :update, :show, :destroy]
  
  def new
    @category = Category.new
  end
  
  def create 
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was successfully created!"
    redirect_to category_path(@category)
    else
      render 'new'
    end
  end
  
  def show
    #@item = Item.find(params[:id]) ovo vise ne treba sada je set_item
  end
  
  def edit
    #@item = Item.find(params[:id]) ovo vise ne treba sada je set_item
  end
  
  def update
    #@item = Item.find(params[:id]) ovo vise ne treba sada je set_item
    if @category.update(category_params)
      flash[:notice] = "Category was successfully updated!"
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end
  
  def index
    @category = Category.all
  end
  
  def destroy
    #@item = Item.find(params[:id]) ovo vise ne treba sada je set_item
    @category.destroy
    flash[:notice] = "Category was successfully deleted!"
    redirect_to category_path(@category)
  end
  
  private
  
  def set_category
    @category = Category.find(params[:id])
  end
  
  def category_params
    params.require(:category).permit(:name)
  end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  def index
    @items = Item.all
  end
  
  def new
    @item = Item.new
  end
  
  def show
   
  end
  
  def edit
    
  end
  
  def update
    
    if @item.update(item_params)
      flash[:notice] = "Item was successfully updated!"
      redirect_to item_path(@item)
    else
      render 'edit'
    end
  end
  
  def create 
    @item = Item.new(item_params)
    @item.user = current_user
    if @item.save
      flash[:notice] = "Item was successfully created!"
    redirect_to item_path(@item)
    else
      render 'new'
    end
  end
  
  
  def destroy
    @item.destroy
    flash[:notice] = "Item was successfully deleted!"
    redirect_to items_path
  end
  
  private
  
  def set_item
    @item = Item.find(params[:id])
  end
  
  def item_params
    params.require(:item).permit(:name, :price, :date)
  end
  
  def require_same_user
      if current_user != @item.user and !current_user.admin?
      flash[:danger] = "You can only edit or delete your own items!"
      redirect_to root_path
      end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]
  
  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to my shopping review #{@user.username}"
      redirect_to user_sesion(@user)
    else
      render 'new'
    end
  end
  
  def edit
  
  end
  
  def update
    if @user.update(user_params)
      flash[:success] = "Your account was successfully updated"
      redirect_to items_path
    else
      render 'edit'
    end
  end
  
  def show
     @user_items = @user.items.paginate(page: params[:page], per_page: 5)
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = "User and all items created by user have been deleted!"
    redirect_to users_session
  end
  
  private
  
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
  
  def set_user
      @user = User.find(params[:id])
  end
  
  def require_same_user
    if current_user != @user and !current_user.admin?
      flash[:danger] = "You can only edit your own account!"
      redirect_to root_path
    end
  end
  
  def require_admin
    if logged_in? and !current_user.admin?
      flash[:danger] = "Only admin users can perform that action!"
      redirect_to root_path
    end
  end
  
end
 

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_form.html.erb
<% if @category.errors.any? %>
<h2>The following errors prevented the category from getting created</h2>
<ul>
<% @category.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
<% end %>
<%= form_for @category do |f| %>
<p>
  <%= f.label :name %><br/>
  <%= f.text_field :name %>
</p>

  <%=f.submit %>
</p>
<% end %>
<%= link_to 'Back to category listing', categories_path %>

app/views/categories/edit.html.erb
<h1>Edit existing Category</h1>
<%= render 'form' %>

app/views/categories/index.html.erb
<h1>Listing all categories</h1>
<p>
  
</p>
<table>
  <tr>
    <th>Category name</th>
  </tr>
  <% @category.each do |category| %>
  <tr>
    <td><%=category.name %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Show', category_path(category) %></td>
    <td><%= link_to 'Delete', category_path(category), method: :delete, data: {confirm: "Are you sure?"} %></td>
  </tr>
  <% end %>
</table>

app/views/categories/new.html.erb
<h1>Create Category</h1>
<%= render 'form' %>

app/views/categories/show.html.erb
<h1>Showing selected category</h1>
<p>
  Category name: <%= @category.name %>
</p>

<%= link_to 'Edit this category', edit_category_path(@category) %>
<%= link_to 'Back to category listing', categories_path %>

app/views/items/_form.html.erb
<% if @item.errors.any? %>
<h2>The following errors prevented the item from getting created</h2>
<ul>
<% @item.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
<% end %>
<%= form_for @item do |f| %>
<p>
  <%= f.label :name %><br/>
  <%= f.text_field :name %>
</p>
<p>
  <%= f.label :price %><br/>
  <%= f.number_field :price, class: :text_field, :step => 0.01, :min => 0.00 %>
</p>
<p>
  <%= f.label :date %><br/>
  <%= f.date_field :date %>
</p>
<p>
  <%=f.submit %>
</p>
<% end %>
<%= link_to 'Back to items listing', items_path %>

app/views/items/edit.html.erb
<h1>Edit existing Item</h1>
<%= render 'form' %>

app/views/items/index.html.erb
<h1>Listing all items</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th>Date of Purchase</th>
  </tr>
  <% @items.each do |item| %>
  <tr>
    <td><%=item.name %></td>
    <td><%=item.price %></td>
    <td><%=item.date %></td>
    <td><%= link_to 'Edit', edit_item_path(item) %></td>
    <td><%= link_to 'Show', item_path(item) %></td>
    <td><%= link_to 'Delete', item_path(item), method: :delete, data: {confirm: "Are you sure?"} %></td>
  <%= link_to @item.user.username, user_session(@item.user) %>
  <%= pluralize(@item.user.item.count, "item") if @item.user.items %>
  <td>Created by:<%= item.user.username if item.user %></td>
  <td><%= time_ago_in_words(item.created_at) %>ago</td>
  <td>last updated:<%= time_ago_in_words(item.updated_at) %>ago</td>
  </tr>
 <% end %>
</table>

app/views/items/new.html.erb
<h1>Create an Item</h1>
<%= render 'form' %>

app/views/items/show.html.erb
<h1>Showing selected item</h1>
<p>
  Name: <%= @item.name %>
</p>
<p>
  Price: <%= @item.price %>
</p>
<p>
  Date of Purchase: <%= @item.date %>
</p>
<%= link_to 'Edit this item', edit_item_path(@item) %>
<%= link_to 'Back to items listing', items_path %>

app/views/layouts/_messages.html.erb
<% flash.each do|name, msg| %>
  <ul>
    <li><%=msg %></li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "My Shopping Review" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%=link_to "My Shopping Review", "/items" %></li>
            <li><%= link_to "Create new item", new_item_path %></li>
            <li><%= link_to "All items", items_path  %></li>
            <li><%= link_to "Create new category", new_category_path %></li>
            <li><%= link_to "All categories", categories_path  %></li>
            <li><%=link_to "Logout", destroy_user_session_path, method: :delete %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= render 'layouts/messages' %>
          <%= yield %>
        </div>
       
      </div><!--/row-->

      <footer>
        <p>&copy; <a href="https://github.com/tatjanatanaskovich">Tatjana Tanasković</a> 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/users/my_shopping.html.erb
<h1>My Shopping</h1>
<%= link_to "My Purchased Items", items_path %><br/><br/>
<%=link_to "Logout", destroy_user_session_path, method: :delete %>

app/views/welcome/about.html.erb
<h1 class="center">My Shopping Review About Page</h1>
<%=link_to'Home', root_path %>

app/views/welcome/index.html.erb
<h1 class="center">Welcome to My Shopping Review</h1>
<%= link_to "My Purchased Items", items_path %><br/><br/>
<%=link_to "Logout", destroy_user_session_path, method: :delete %>